---
AWSTemplateFormatVersion: "2010-09-09"
Description: Github Actions configuration - OIDC IAM IdP and associated role CI/CD

Resources:

  IdpGitHubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
        - !Sub https://github.com/atlas-school-classroom/*
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      Tags:
        - Key: Name
          Value: AtlasGitHubClassroomRole-OIDC-Provider

  RoleGithubActions:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AtlasGitHubClassroomRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !If
                - !Ref IdpGitHubOidc
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:atlas-school-classroom/*:ref:refs/heads/main
      ManagedPolicyArns:
        ## edit the managed policy to give least privileges
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess

Outputs:

  IdpGitHubOidc:
    Description: "ARN of Github OIDC Provider"
    Value: !GetAtt IdpGitHubOidc.Arn

  RoleGithubActionsARN:
    Description: "CICD Role for GitHub Actions"
    Value: !GetAtt RoleGithubActions.Arn
